version: '3.8'

services:
  actual-budget-normalizer:
    build: .
    container_name: actual-budget-normalizer-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=/app/jobs.db
      - CATEGORIES_FILE=/app/categories.json
      - PAYEES_FILE=/app/payees.json
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=actual-bucket
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - minio
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio-bucket
    ports:
      - "9005:9000"
      - "9006:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
