line-length = 120
exclude = ["__pycache__", ".venv", "build", "dist"]
select = [
  "E",
  "F",
  "W",
  "I",
  "UP",
  "C90",
  "N",
  "D",
  "ANN",
  "S",
  "B",
  "A",
  "C4",
  "DTZ",
  "EM",
  "ISC",
  "ICN",
  "PIE",
  "PT",
  "Q",
  "RET",
  "SIM",
  "TID",
  "ARG",
  "PTH",
  "ERA",
  "PD",
  "PGH",
  "PL",
  "TRY",
  "RUF",
]
ignore = []
